apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: hertl-adv-daba-26
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:4.4.15-community
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_AUTH
              value: "neo4j/test"
          resources:
            requests:
              cpu: "2"
              memory: "3000Mi"
            limits:
              cpu: "2"
              memory: "3000Mi"
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data